run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - bodyclose
    - noctx

linters-settings:
  gosec:
    excludes:
      - G401  # Use of weak cryptographic primitive (not applicable here)

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - gosec
